# Generated by Django 4.2 on 2023-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='Date',
            field=models.DateField(),
        ),
    ]
